CREATE DATABASE vietspiderdb CHARACTER SET UTF8;

DELETE FROM CONTENT WHERE META_ID = 200711081701480371;
DELETE FROM RELATION WHERE META_ID = 200711081701480371;
DELETE FROM META WHERE ID = 200711081701480371;

ALTER TABLE META ADD FOREIGN KEY (DOMAIN_ID) REFERENCES DOMAIN (ID);

ALTER TABLE CONTENT ADD FOREIGN KEY (META_ID) REFERENCES META (ID);
ALTER TABLE RELATION ADD FOREIGN KEY (META_ID) REFERENCES META (ID);
ALTER TABLE IMAGE ADD FOREIGN KEY (META_ID) REFERENCES META (ID);

ALTER TABLE META ADD INDEX (ID);

ALTER TABLE DOMAIN ADD INDEX (ID);
